version: '2.1'

services:
  config-service:
    image: arnia-config-service
    container_name: "config-service.arnia.ro"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    ports:
      - "8888:8888"
    expose:
      - "8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-service:
    image: arnia-discovery-service
    container_name: "discovery-service.arnia.ro"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8761:8761"
    expose:
      - "8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    container_name: "auth-mongodb.arnia.ro"
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      INIT_DUMP: initial-auth-dump.js
      DB_NAME: $AUTH_DB_NAME
    restart: always
    ports:
      - "5001:27017"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ADMIN_SERVICE_PASSWORD: $ADMIN_SERVICE_PASSWORD
      PARTY_SERVICE_PASSWORD: $PARTY_SERVICE_PASSWORD
    image: arnia-auth-service
    container_name: "auth-service.arnia.ro"
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "5000:5000"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  api-gateway:
    image: arnia-api-gateway
    container_name: "api-gateway.arnia.ro"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  admin-mongodb:
    container_name: "admin-mongodb.arnia.ro"
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      INIT_DUMP: initial-admin-dump.js
      DB_NAME: $ADMIN_DB_NAME
    restart: always
    ports:
      - "5002:27017"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  admin-service:
    image: arnia-admin-service
    container_name: "admin-service.arnia.ro"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8001:8001"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring-service:
    image: arnia-monitoring-service
    container_name: "monitoring-service.arnia.ro"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "9000:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  turbine-stream-service:
    image: arnia-turbine-stream-service
    container_name: "turbine-stream-service.arnia.ro"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8989:8989"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq.arnia.ro"
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
